# Generated by Django 4.2.7 on 2023-11-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='HW-DRF/', verbose_name='картинка'),
        ),
    ]
