# Generated by Django 4.2.7 on 2023-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_lessons_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='image',
            field=models.ImageField(null=True, upload_to='HW-DRF/', verbose_name='картинка'),
        ),
    ]
