# Generated by Django 4.2.7 on 2023-11-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_lessons_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='image',
            field=models.ImageField(null=True, upload_to='HW-DRF/', verbose_name='картинка'),
        ),
    ]
